add /landing route & dump header component
shadyvb/randoms pull request #5
Opened 2021-03-22 12:09 UTC by msharafjr

2021-03-22 12:20 UTC, shadyvb commented on src/app/components/header.tsx
> +import {Sidebar} from './sidebar';
Components should be exported as defaults as a general rule.

2021-03-22 12:20 UTC, shadyvb commented on src/app/components/header.tsx
> +  <a className={cx('__logo')} href='/'>
This should also be a `Link` component.

2021-03-22 12:20 UTC, shadyvb commented on src/app/components/header.tsx
> +const Logo = () => (
One component per file.

2021-03-22 12:24 UTC, shadyvb commented on src/app/routes/index.ts
> +const routes: route[] = [home, landing, catchall];
Replace `landing` with `home`, we don't need the existing home anymore.

2021-03-22 12:24 UTC, shadyvb requested changes
.

2021-03-22 13:25 UTC, shadyvb commented on src/app/components/social-links.tsx
> +const SocilLinks = () => (
```suggestion
const SocialLinks = () => (
```

2021-03-22 13:26 UTC, shadyvb commented on src/app/components/sidebar.tsx
> +  <div className={cx('__side-nav')}>+</div>
Class names should match the component name as much as possible.

2021-03-22 13:26 UTC, shadyvb commented on src/app/components/nav-menu.tsx
> +const NavLink = (props: any) => {
Duplicate component.

2021-03-22 13:26 UTC, shadyvb commented on src/app/routes/counter.tsx
> +import React from "react";
Need to remove this route.

2021-03-22 13:27 UTC, shadyvb requested changes
.

2021-03-24 14:23 UTC, msharafjr commented
@shadyvb

2021-03-24 14:45 UTC, shadyvb approved these changes
Okay, I give up, we'll fix it later 😒

2021-03-25 11:55 UTC, merged