Add category hook demo
shadyvb/randoms pull request #8
Opened 2021-03-23 13:50 UTC by msharafjr

2021-03-23 13:54 UTC, shadyvb requested changes
Categories are arrays, and they have a slug and a name.

2021-03-24 11:18 UTC, shadyvb requested changes

2021-03-24 11:18 UTC, shadyvb commented on src/app/store/hooks/usePost.tsx
> +        categories: [useCategory(1)],
Spacing here is not correct, make sure spacing is automatically fixed in your editor. It should happen automatically if you have TSLint installed in vscode.

2021-03-24 11:18 UTC, shadyvb commented on src/app/store/types/post.ts
> +import {Category} from './category';
Spacing issues here as well.

2021-03-25 13:46 UTC, msharafjr commented
@shadyvb

2021-03-25 13:48 UTC, shadyvb requested changes

2021-03-25 13:48 UTC, shadyvb commented on src/app/store/types/post.ts
> +        _thumbnail: Attachment,
It is `_thumbnail_id`, that's the API definition

2021-03-25 13:56 UTC, msharafjr commented
@shadyvb

2021-03-29 07:07 UTC, shadyvb approved these changes

2021-03-29 07:07 UTC, merged